POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer .eyJ1c2VybmFtZSI6ImRhdmlkIiwiaWQiOiI2NmU2OTkyNjcwZGZmZmQyYTkzNzkxYjAiLCJpYXQiOjE3MjY1MDg3MDB9.TWVWhvnVRzrpNaYPWatU_uBkh9ipAKeSZAfttXJeUfM

{
    "title": "Test blog 2222",
    "author": "test author", 
    "url": "www.test-url.com",
    "likes": 100,
    "userId": "66e69b93261b8904c841b1f0"
}