POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkIiwiaWQiOiI2NzhiODBkYjNiZjNlNmQ5MmU5ZWUyYjEiLCJpYXQiOjE3MzcyOTUwMTN9.49EwWsoAmKXutsP1LpxMO14zUM1qilOk2qsbI187MHU

{
    "title": "Test blog 1",
    "author": "test author", 
    "url": "www.test-url.com",
    "likes": 100,
    "comments": ["test", "testing"]
}